name: marvelapp
description: Marvel App

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  dio: ^5.0.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.2
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  card_swiper: ^2.0.4
  pinput: ^2.2.31
  percent_indicator: ^4.2.3
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  shared_preferences: ^2.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  google_fonts: ^4.0.3
  build_runner: ^2.3.3

  

flutter:


  uses-material-design: true

  assets:
  - assets/images/
  - assets/svg/
  